### ISSUE TITLE
Add support for fine-tuning MusicGen

### ISSUE THREAD

**Issue by joehoover** [replicate/cog-musicgen-melody#2]
I want to fine-tune MusicGen on my own music. 

```[tasklist]
### Tasks
- [ ] https://github.com/replicate/cog-musicgen/issues/3
- [ ] https://github.com/replicate/cog-musicgen/issues/4
- [ ] Make model trainable on replicate
- [ ] Write blog post about training MusicGen
```

**Comment by andreasjansson** [comment]
@nateraw has been working on this as well.

**Comment by sakemin** [comment]
Should we close this issue?
