### ISSUE TITLE
Implement preprocessor for training data

### ISSUE THREAD

**Issue by joehoover** [replicate/cog-musicgen-melody#3]
```[tasklist]
### Tasks
- [x] Extract audio from YouTube
- [x] Break audio into segments, given cut points
- [x] Detect cutpoints for audio segmentation based on periods of silence
- [x] Create sliding windows over segments given a duration and length of overlap
- [x] Generate data map that links audio files to metadata
- [ ] Implement analyzer class for deriving measurements from audio for annotation
```
